Updating pyvista2vtk from class refactoring
Pasting the previous error code of:
Traceback (most recent call last):
  File "C:\Users\Waqas Hussain\OneDrive - Universit� degli Studi di Milano-Bicocca\Documents\GitHub\PZero\pzero\project_window.py", line 153, in <lambda>
    self.actionImportPyvista.triggered.connect(lambda: pyvista2vtk(self=self))
                                                       ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Waqas Hussain\OneDrive - Universit� degli Studi di Milano-Bicocca\Documents\GitHub\PZero\pzero\imports\pyvista2vtk.py", line 83, in pyvista2vtk
    self.e_c.add_entity_from_dict(
    ^^^^^^^^
AttributeError: 'ProjectWindow' object has no attribute 'e_c'
Adding comments from previous code

of fixing it by assigning the right collection to pyvista2vtk. Also, adding support PySide6 by getting the Qfile Dialog from PysideQtWidgets in a right way instead.

Before the commit it was PyQt5 as an import for file dialog, its now qtpy.QtWidgets because of upgradation to PySide6.

replacing e_c collection with a geological collection so that pyvista file goes into the right place.